version: '3.7'

services:
  nginx:
    container_name: tb-core-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    volumes:
      - .:/var/www
      - 'tbcorestorage:/var/www/storage'
    ports:
      - '${APP_PORT}:80'
    links:
      - "core:php-fpm"
    depends_on:
      - "core"
    networks:
      - tbcorenet
  core:
    container_name: tb-core
    build:
      context: .
      dockerfile: Dockerfile-phpfpm
    restart: always
    volumes:
      - .:/var/www
      - 'tbcorestorage:/var/www/storage'
    links:
      - "cache:redis"
    depends_on:
      - "cache"
    networks:
      - tbcorenet
  cache:
    container_name: tb-core-cache
    image: redis:6-alpine
    restart: always
    networks:
      - tbcorenet

networks:
  tbcorenet:
    driver: bridge

volumes:
  tbcorestorage:
    driver: local
