name: CI Trawlbens Core Project

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy existing storage directory and Configuration
      run: |
        cp -f /home/github-runner/_work/TBCORE/composer.lock .
        cp -f /home/github-runner/_work/TBCORE/.env .
        cp -f /home/github-runner/_work/TBCORE/.gitignore .
        cp -rf /home/github-runner/_work/TBCORE/storage .
        cp -f composer.lock /home/github-runner/_work/TBCORE
        cp -f .env /home/github-runner/_work/TBCORE
        cp -f .gitignore /home/github-runner/_work/TBCORE
        cp -rf storage /home/github-runner/_work/TBCORE
    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Install Dependencies
      run: |
          npm install
          npm run prod
          
    - name: Copy storage and configuration back
      run: |
        cp -f /home/github-runner/_work/TBCORE/composer.lock .
        cp -f /home/github-runner/_work/TBCORE/.env .
        cp -f /home/github-runner/_work/TBCORE/.gitignore .
        cp -rf /home/github-runner/_work/TBCORE/storage .
        php artisan optimize
