name: CI Trawlbens Core Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy Necessary File
      run: cp /home/github-runner/_work/TBCORE/* /home/github-runner/_work/trawlbens.core/trawlbens.core
    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Install Dependencies
      run: |
        if git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep -qE '^(.*\.js|.*\.jsx|.*\.ts|.*\.tsx|.*\.vue)$'; then
          npm install
          npm run prod
        else
          php artisan optimize
        fi
  
    
