name: CI Trawlbens Core Project

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Install Dependencies
      run: |
        if git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep -qE '^(.*\.js|.*\.jsx|.*\.ts|.*\.tsx|.*\.vue)$'; then
          npm install
          npm run prod
        else
          php artisan optimize
        fi
    - name: Send Telegram Notification TB Core
      run: |
        curl -s -X POST https://api.telegram.org/bot6066215459:AAEZkNoW2WbDV9CeqPVNko79OQ9_7POyKm8/sendMessage?chat_id=-100180884345 \
        -d text="The CI build for the Trawlbens Core project has completed."
    
