# name: CI Trawlbens Core Project

# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     # runs-on: self-hosted
#     runs-on: ubuntu-latest

#     steps:
#     - name: send telegram message on push
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: |
#           ${{ github.actor }} created commit:
#           Commit message: ${{ github.event.commits[0].message }}
          
#           Branch: *${{ github.ref }}*
#           Repository: *${{ github.repository }}*
          
#           See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


name: CI/CD for Trawlbens Core Branch Staging and Develop
on:
  push:
    branches:
      - staging
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
    - name: Deploy using Username Password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST_IP }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
         cd /home/deployer/repo/tbcore
         git pull origin staging
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          
          Branch: *${{ github.ref }}*
          Repository: *${{ github.repository }}*
          
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  deploy-develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: Deploy using Username Password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST_IP }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
         cd /home/deployer/repo/tbcore-develop
         git pull origin develop
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          
          Branch: *${{ github.ref }}*
          Repository: *${{ github.repository }}*
          
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
